from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
import requests
from datetime import datetime, timedelta

router = APIRouter(
    tags=["Currency"],
    responses={404: {"description": "Not found"}},
)

@router.get('/rate')
async def get_currency_rate(base_currency: str = 'eur', target_currency: str = 'rub', days: int = 10):
    rates = {}
    end_date = datetime.now()
    
    for i in range(days):
        current_date = (end_date - timedelta(days=i)).strftime('%Y-%m-%d')
        url = f"https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@{current_date}/v1/currencies/{base_currency}.json"
        
        try:
            response = requests.get(url)
            data = response.json()
            
            if base_currency in data:
                rate = data[base_currency].get(target_currency)
                if rate is not None:
                    rates[current_date] = rate
                else:
                    rates[current_date] = 'N/A'
            
        except Exception as e:
            rates[current_date] = 'N/A'
            continue
    
    return JSONResponse(content=rates)

# Список валют
currencies = [
    ("1000sats", "", ""),
    ("1inch", "1inch", "1inch"),
    ("aave", "Aave", "Aave"),
    ("ada", "Cardano", "Кардано"),
    ("aed", "Emirati Dirham", "Эмиратский дирхам"),
    ("afn", "Afghan Afghani", "Афганский афгани"),
    ("agix", "SingularityNET", "SingularityNET"),
    ("akt", "Akash Network", "Akash Network"),
    ("algo", "Algorand", "Algorand"),
    ("all", "Albanian Lek", "Албанский лек"),
    ("amd", "Armenian Dram", "Армянский драм"),
    ("amp", "Amp", "Amp"),
    ("ang", "Dutch Guilder", "Голландский гульден"),
    ("aoa", "Angolan Kwanza", "Ангольская кванза"),
    ("ape", "ApeCoin", "ApeCoin"),
    ("apt", "Aptos", "Aptos"),
    ("ar", "Arweave", "Arweave"),
    ("arb", "Arbitrum", "Arbitrum"),
    ("ars", "Argentine Peso", "Аргентинское песо"),
    ("atom", "Cosmos", "Космос"),
    ("ats", "Austrian Schilling", "Австрийский шиллинг"),
    ("aud", "Australian Dollar", "Австралийский доллар"),
    ("avax", "Avalanche", "Авеланч"),
    ("awg", "Aruban or Dutch Guilder", "Арубанский или голландский гульден"),
    ("axs", "Axie Infinity", "Axie Infinity"),
    ("azm", "Azerbaijani Manat", "Азербайджанский манат"),
    ("azn", "Azerbaijan Manat", "Азербайджанский манат"),
    ("bake", "BakeryToken", "BakeryToken"),
    ("bam", "Bosnian Convertible Mark", "Боснийская конвертируемая марка"),
    ("bat", "Basic Attention Token", "Basic Attention Token"),
    ("bbd", "Barbadian or Bajan Dollar", "Барбадосский доллар"),
    ("bch", "Bitcoin Cash", "Bitcoin Cash"),
    ("bdt", "Bangladeshi Taka", "Бангладешская така"),
    ("bef", "Belgian Franc", "Бельгийский франк"),
    ("bgn", "Bulgarian Lev", "Болгарский лев"),
    ("bhd", "Bahraini Dinar", "Бахрейнский динар"),
    ("bif", "Burundian Franc", "Бурундийский франк"),
    ("bmd", "Bermudian Dollar", "Бермудский доллар"),
    ("bnb", "Binance Coin", "Бинанс Коин"),
    ("bnd", "Bruneian Dollar", "Брунейский доллар"),
    ("bob", "Bolivian Bolíviano", "Боливийский боливиано"),
    ("brl", "Brazilian Real", "Бразильский реал"),
    ("bsd", "Bahamian Dollar", "Багамский доллар"),
    ("bsv", "Bitcoin SV", "Bitcoin SV"),
    ("bsw", "Biswap", "Biswap"),
    ("btc", "Bitcoin", "Биткоин"),
    ("btcb", "Bitcoin BEP2", "Bitcoin BEP2"),
    ("btg", "Bitcoin Gold", "Bitcoin Gold"),
    ("btn", "Bhutanese Ngultrum", "Бутанский нгултрум"),
    ("btt", "BitTorrent", "BitTorrent"),
    ("busd", "Binance USD", "Binance USD"),
    ("bwp", "Botswana Pula", "Ботсванская пула"),
    ("byn", "Belarusian Ruble", "Белорусский рубль"),
    ("byr", "Belarusian Ruble", "Белорусский рубль"),
    ("bzd", "Belizean Dollar", "Белизский доллар"),
    ("cad", "Canadian Dollar", "Канадский доллар"),
    ("cake", "PancakeSwap", "PancakeSwap"),
    ("cdf", "Congolese Franc", "Конголезский франк"),
    ("celo", "Celo", "Celo"),
    ("cfx", "Conflux", "Conflux"),
    ("chf", "Swiss Franc", "Швейцарский франк"),
    ("chz", "Chiliz", "Chiliz"),
    ("clp", "Chilean Peso", "Чилийское песо"),
    ("cnh", "Chinese Yuan Renminbi Offshore", "Китайский юань оффшорный"),
    ("cny", "Chinese Yuan Renminbi", "Китайский юань"),
    ("comp", "Compound", "Compound"),
    ("cop", "Colombian Peso", "Колумбийское песо"),
    ("crc", "Costa Rican Colon", "Коста-риканский колон"),
    ("cro", "Crypto.com Chain", "Crypto.com Chain"),
    ("crv", "Curve DAO Token", "Curve DAO Token"),
    ("cspr", "Casper", "Casper"),
    ("cuc", "Cuban Convertible Peso", "Кубинское конвертируемое песо"),
    ("cup", "Cuban Peso", "Кубинское песо"),
    ("cve", "Cape Verdean Escudo", "Кабо-Верде эскудо"),
    ("cvx", "Convex Finance", "Convex Finance"),
    ("cyp", "Cypriot Pound", "Кипрский фунт"),
    ("czk", "Czech Koruna", "Чешская крона"),
    ("dai", "DAI", "DAI"),
    ("dash", "Digital Cash", "Digital Cash"),
    ("dcr", "Decred", "Decred"),
    ("dem", "German Deutsche Mark", "Немецкая марка"),
    ("dfi", "DfiStarter", "DfiStarter"),
    ("djf", "Djiboutian Franc", "Джибутийский франк"),
    ("dkk", "Danish Krone", "Датская крона"),
    ("doge", "Dogecoin", "Догкоин"),
    ("dop", "Dominican Peso", "Доминиканское песо"),
    ("dot", "Polkadot", "Полкадот"),
    ("dydx", "dYdX", "dYdX"),
    ("dzd", "Algerian Dinar", "Алжирский динар"),
    ("eek", "Estonian Kroon", "Эстонская крона"),
    ("egld", "Elrond", "Elrond"),
    ("egp", "Egyptian Pound", "Египетский фунт"),
    ("enj", "Enjin Coin", "Enjin Coin"),
    ("eos", "EOS", "EOS"),
    ("ern", "Eritrean Nakfa", "Эритрейская накфа"),
    ("esp", "Spanish Peseta", "Испанская песета"),
    ("etb", "Ethiopian Birr", "Эфиопский быр"),
    ("etc", "Ethereum Classic", "Эфириум Классик"),
    ("eth", "Ethereum", "Эфириум"),
    ("eur", "Euro", "Евро"),
    ("fei", "Fei USD", "Fei USD"),
    ("fil", "Filecoin", "Filecoin"),
    ("fim", "Finnish Markka", "Финская марка"),
    ("fjd", "Fijian Dollar", "Фиджийский доллар"),
    ("fkp", "Falkland Island Pound", "Фунт Фолклендских островов"),
    ("flow", "Flow", "Flow"),
    ("flr", "FLARE", "FLARE"),
    ("frax", "Frax", "Frax"),
    ("frf", "French Franc", "Французский франк"),
    ("ftm", "Fantom", "Fantom"),
    ("ftt", "FarmaTrust", "FarmaTrust"),
    ("fxs", "Frax Share", "Frax Share"),
    ("gala", "Gala", "Gala"),
    ("gbp", "British Pound", "Британский фунт"),
    ("gel", "Georgian Lari", "Грузинский лари"),
    ("ggp", "Guernsey Pound", "Гернсийский фунт"),
    ("ghc", "Ghanaian Cedi", "Ганский седи"),
    ("ghs", "Ghanaian Cedi", "Ганский седи"),
    ("gip", "Gibraltar Pound", "Гибралтарский фунт"),
    ("gmd", "Gambian Dalasi", "Гамбийский даласи"),
    ("gmx", "Goldmaxcoin", "Goldmaxcoin"),
    ("gnf", "Guinean Franc", "Гвинейский франк"),
    ("gno", "Gnosis", "Gnosis"),
    ("grd", "Greek Drachma", "Греческая драхма"),
    ("grt", "The Graph", "The Graph"),
    ("gt", "GateToken", "GateToken"),
    ("gtq", "Guatemalan Quetzal", "Гватемальский кетсаль"),
    ("gusd", "Gemini US Dollar", "Gemini US Dollar"),
    ("gyd", "Guyanese Dollar", "Гайанский доллар"),
    ("hbar", "Hedera", "Hedera"),
    ("hkd", "Hong Kong Dollar", "Гонконгский доллар"),
    ("hnl", "Honduran Lempira", "Гондурасская лемпира"),
    ("hnt", "Helium", "Helium"),
    ("hot", "Hydro Protocol", "Hydro Protocol"),
    ("hrk", "Croatian Kuna", "Хорватская куна"),
    ("ht", "Huobi Token", "Huobi Token"),
    ("htg", "Haitian Gourde", "Гаитянский гурд"),
    ("huf", "Hungarian Forint", "Венгерский форинт"),
    ("icp", "Internet Computer", "Internet Computer"),
    ("idr", "Indonesian Rupiah", "Индонезийская рупия"),
    ("iep", "Irish Pound", "Ирландский фунт"),
    ("ils", "Israeli Shekel", "Израильский шекель"),
    ("imp", "Isle of Man Pound", "Фунт острова Мэн"),
    ("imx", "Immutable X", "Immutable X"),
    ("inj", "Injective", "Injective"),
    ("inr", "Indian Rupee", "Индийская рупия"),
    ("iqd", "Iraqi Dinar", "Иракский динар"),
    ("irr", "Iranian Rial", "Иранский риал"),
    ("isk", "Icelandic Krona", "Исландская крона"),
    ("itl", "Italian Lira", "Итальянская лира"),
    ("jep", "Jersey Pound", "Джерсийский фунт"),
    ("jmd", "Jamaican Dollar", "Ямайский доллар"),
    ("jod", "Jordanian Dinar", "Иорданский динар"),
    ("jpy", "Japanese Yen", "Японская иена"),
    ("kas", "", ""),
    ("kava", "Kava", "Kava"),
    ("kcs", "Kucoin", "Kucoin"),
    ("kda", "Kadena", "Kadena"),
    ("kes", "Kenyan Shilling", "Кенийский шиллинг"),
    ("kgs", "Kyrgyzstani Som", "Киргизский сом"),
    ("khr", "Cambodian Riel", "Камбоджийский риель"),
    ("klay", "Klaytn", "Klaytn"),
    ("kmf", "Comorian Franc", "Коморский франк"),
    ("knc", "Kyber Network Crystals", "Kyber Network Crystals"),
    ("kpw", "North Korean Won", "Северокорейская вона"),
    ("krw", "South Korean Won", "Южнокорейская вона"),
    ("ksm", "Kusama", "Kusama"),
    ("kwd", "Kuwaiti Dinar", "Кувейтский динар"),
    ("kyd", "Caymanian Dollar", "Кайманский доллар"),
    ("kzt", "Kazakhstani Tenge", "Казахстанский тенге"),
    ("lak", "Lao Kip", "Лаосский кип"),
    ("lbp", "Lebanese Pound", "Ливанский фунт"),
    ("ldo", "Lido DAO Token", "Lido DAO Token"),
    ("leo", "LEOcoin", "LEOcoin"),
    ("link", "Chainlink", "Чейнлинк"),
    ("lkr", "Sri Lankan Rupee", "Шри-ланкийская рупия"),
    ("lrc", "Loopring", "Loopring"),
    ("lrd", "Liberian Dollar", "Либерийский доллар"),
    ("lsl", "Basotho Loti", "Басуто лоти"),
    ("ltc", "Litecoin", "Лайткоин"),
    ("ltl", "Lithuanian Litas", "Литовский лит"),
    ("luf", "Luxembourg Franc", "Люксембургский франк"),
    ("luna", "Terra", "Terra"),
    ("lunc", "", ""),
    ("lvl", "Latvian Lat", "Латвийский лат"),
    ("lyd", "Libyan Dinar", "Ливийский динар"),
    ("mad", "Moroccan Dirham", "Марокканский дирхам"),
    ("mana", "Mana Coin Decentraland", "Mana Coin Decentraland"),
    ("matic", "Polygon", "Полигон"),
    ("mbx", "MobieCoin", "MobieCoin"),
    ("mdl", "Moldovan Leu", "Молдавский лей"),
    ("mga", "Malagasy Ariary", "Малагасийский ариари"),
    ("mgf", "Malagasy Franc", "Малагасийский франк"),
    ("mina", "Mina", "Mina"),
    ("mkd", "Macedonian Denar", "Македонский денар"),
    ("mkr", "Maker", "Maker"),
    ("mmk", "Burmese Kyat", "Бирманский кьят"),
    ("mnt", "Mongolian Tughrik", "Монгольский тугрик"),
    ("mop", "Macau Pataca", "Макао патака"),
    ("mro", "Mauritanian Ouguiya", "Мавританская угия"),
    ("mru", "Mauritanian Ouguiya", "Мавританская угия"),
    ("mtl", "Maltese Lira", "Мальтийская лира"),
    ("mur", "Mauritian Rupee", "Маврикийская рупия"),
    ("mvr", "Maldivian Rufiyaa", "Мальдивская руфия"),
    ("mwk", "Malawian Kwacha", "Малавийская квача"),
    ("mxn", "Mexican Peso", "Мексиканское песо"),
    ("mxv", "", ""),
    ("myr", "Malaysian Ringgit", "Малайзийский ринггит"),
    ("mzm", "Mozambican Metical", "Мозамбикский метикал"),
    ("mzn", "Mozambican Metical", "Мозамбикский метикал"),
    ("nad", "Namibian Dollar", "Намибийский доллар"),
    ("near", "NEAR Protocol", "NEAR Протокол"),
    ("neo", "NEO", "NEO"),
    ("nexo", "NEXO", "NEXO"),
    ("nft", "NFT", "NFT"),
    ("ngn", "Nigerian Naira", "Нигерийская найра"),
    ("nio", "Nicaraguan Cordoba", "Никарагуанская кордоба"),
    ("nlg", "Dutch Guilder", "Голландский гульден"),
    ("nok", "Norwegian Krone", "Норвежская крона"),
    ("npr", "Nepalese Rupee", "Непальская рупия"),
    ("nzd", "New Zealand Dollar", "Новозеландский доллар"),
    ("okb", "Okex", "Okex"),
    ("omr", "Omani Rial", "Оманский риал"),
    ("one", "Menlo One", "Menlo One"),
    ("op", "Optimism", "Optimism"),
    ("ordi", "", ""),
    ("pab", "Panamanian Balboa", "Панамский бальбоа"),
    ("paxg", "PAX Gold", "PAX Gold"),
    ("pen", "Peruvian Sol", "Перуанский соль"),
    ("pepe", "", ""),
    ("pgk", "Papua New Guinean Kina", "Папуа-новогвинейская кина"),
    ("php", "Philippine Peso", "Филиппинское песо"),
    ("pkr", "Pakistani Rupee", "Пакистанская рупия"),
    ("pln", "Polish Zloty", "Польский злотый"),
    ("pte", "Portuguese Escudo", "Португальский эскудо"),
    ("pyg", "Paraguayan Guarani", "Парагвайский гуарани"),
    ("qar", "Qatari Riyal", "Катарский риал"),
    ("qnt", "Quant", "Quant"),
    ("qtum", "QTUM", "QTUM"),
    ("rol", "Romanian Leu", "Румынский лей"),
    ("ron", "Romanian Leu", "Румынский лей"),
    ("rpl", "Rocket Pool", "Rocket Pool"),
    ("rsd", "Serbian Dinar", "Сербский динар"),
    ("rub", "Russian Ruble", "Российский рубль"),
    ("rune", "THORChain (ERC20)", "THORChain (ERC20)"),
    ("rvn", "Ravencoin", "Ravencoin"),
    ("rwf", "Rwandan Franc", "Руандийский франк"),
    ("sand", "The Sandbox", "The Sandbox"),
    ("sar", "Saudi Arabian Riyal", "Саудовский риял"),
    ("sbd", "Solomon Islander Dollar", "Доллар Соломоновых островов"),
    ("scr", "Seychellois Rupee", "Сейшельская рупия"),
    ("sdd", "Sudanese Dinar", "Суданский динар"),
    ("sdg", "Sudanese Pound", "Суданский фунт"),
    ("sek", "Swedish Krona", "Шведская крона"),
    ("sgd", "Singapore Dollar", "Сингапурский доллар"),
    ("shib", "Shiba Inu", "Шиба Ину"),
    ("shp", "Saint Helenian Pound", "Фунт Святой Елены"),
    ("sit", "Slovenian Tolar", "Словенский толар"),
    ("skk", "Slovak Koruna", "Словацкая крона"),
    ("sle", "Sierra Leonean Leone", "Сьерра-леонский леоне"),
    ("sll", "Sierra Leonean Leone", "Сьерра-леонский леоне"),
    ("snx", "Synthetix Network", "Synthetix Network"),
    ("sol", "Solana", "Солана"),
    ("sos", "Somali Shilling", "Сомалийский шиллинг"),
    ("spl", "Seborgan Luigino", "Себорга луйджино"),
    ("srd", "Surinamese Dollar", "Суринамский доллар"),
    ("srg", "Surinamese Guilder", "Суринамский гульден"),
    ("std", "Sao Tomean Dobra", "Добра Сан-Томе и Принсипи"),
    ("stn", "Sao Tomean Dobra", "Добра Сан-Томе и Принсипи"),
    ("stx", "Stacks", "Stacks"),
    ("sui", "Sui", "Sui"),
    ("svc", "Salvadoran Colon", "Сальвадорский колон"),
    ("syp", "Syrian Pound", "Сирийский фунт"),
    ("szl", "Swazi Lilangeni", "Свазилендский лилангени"),
    ("thb", "Thai Baht", "Тайский бат"),
    ("theta", "Theta", "Theta"),
    ("tjs", "Tajikistani Somoni", "Таджикский сомони"),
    ("tmm", "Turkmenistani Manat", "Туркменский манат"),
    ("tmt", "Turkmenistani Manat", "Туркменский манат"),
    ("tnd", "Tunisian Dinar", "Тунисский динар"),
    ("ton", "Tokamak Network", "Tokamak Network"),
    ("top", "Tongan Pa'anga", "Тонганская паанга"),
    ("trl", "", ""),
    ("trx", "TRON", "TRON"),
    ("try", "Turkish Lira", "Турецкая лира"),
    ("ttd", "Trinidadian Dollar", "Доллар Тринидада и Тобаго"),
    ("ttt", "Tap Project", "Tap Project"),
    ("tusd", "True USD", "True USD"),
    ("tvd", "Tuvaluan Dollar", "Тувалуанский доллар"),
    ("twd", "Taiwan New Dollar", "Новый тайваньский доллар"),
    ("twt", "Trust Wallet Token", "Trust Wallet Token"),
    ("tzs", "Tanzanian Shilling", "Танзанийский шиллинг"),
    ("uah", "Ukrainian Hryvnia", "Украинская гривна"),
    ("ugx", "Ugandan Shilling", "Угандийский шиллинг"),
    ("uni", "Uniswap", "Юнисвап"),
    ("usd", "US Dollar", "Доллар США"),
    ("usdc", "USDC", "USDC"),
    ("usdd", "", ""),
    ("usdp", "USDP Stablecoin", "USDP Stablecoin"),
    ("usdt", "Tether", "Тезер"),
    ("uyu", "Uruguayan Peso", "Уругвайское песо"),
    ("uzs", "Uzbekistani Som", "Узбекский сум"),
    ("val", "Vatican City Lira", "Ватиканская лира"),
    ("veb", "Venezuelan Bolívar", "Венесуэльский боливар"),
    ("ved", "", ""),
    ("vef", "Venezuelan Bolívar", "Венесуэльский боливар"),
    ("ves", "Venezuelan Bolívar", "Венесуэльский боливар"),
    ("vet", "Vechain", "Vechain"),
    ("vnd", "Vietnamese Dong", "Вьетнамский донг"),
    ("vuv", "Ni-Vanuatu Vatu", "Вануатский вату"),
    ("waves", "Waves", "Waves"),
    ("wemix", "WEMIX", "WEMIX"),
    ("woo", "WOO Network", "WOO Network"),
    ("wst", "Samoan Tala", "Самоанская тала"),
    ("xaf", "Central African CFA Franc BEAC", "Франк КФА BEAC"),
    ("xag", "Silver Ounce", "Серебро (тройская унция)"),
    ("xau", "Gold Ounce", "Золото (тройская унция)"),
    ("xaut", "Tether Gold", "Tether Gold"),
    ("xbt", "", ""),
    ("xcd", "East Caribbean Dollar", "Восточно-карибский доллар"),
    ("xch", "Chia", "Chia"),
    ("xdc", "XDC Network", "XDC Network"),
    ("xdr", "IMF Special Drawing Rights", "Специальные права заимствования"),
    ("xec", "Eternal Coin", "Eternal Coin"),
    ("xem", "NEM", "NEM"),
    ("xlm", "Stellar Lumen", "Stellar Lumen"),
    ("xmr", "Monero", "Монеро"),
    ("xof", "CFA Franc", "Франк КФА"),
    ("xpd", "Palladium Ounce", "Палладий (тройская унция)"),
    ("xpf", "CFP Franc", "Франк КФП"),
    ("xpt", "Platinum Ounce", "Платина (тройская унция)"),
    ("xrp", "Ripple", "Рипл"),
    ("xtz", "Tezos", "Tezos"),
    ("yer", "Yemeni Rial", "Йеменский риал"),
    ("zar", "South African Rand", "Южноафриканский рэнд"),
    ("zec", "ZCash", "ZCash"),
    ("zil", "Zilliqa", "Zilliqa"),
    ("zmk", "Zambian Kwacha", "Замбийская квача"),
    ("zmw", "Zambian Kwacha", "Замбийская квача"),
    ("zwd", "Zimbabwean Dollar", "Зимбабвийский доллар"),
    ("zwg", "", ""),
    ("zwl", "Zimbabwean Dollar", "Зимбабвийский доллар")
]
